#!/usr/bin/env python3
"""Render each paste-thread candidate as a coordination-page markdown file.

Reads   outputs/candidates.jsonl (produced by build_candidates.py)
        agent-logs/<host>/revisions.jsonl (looked up by page_id)
Writes  outputs/threads/<thread_id>.md, one per candidate.

Output shape matches the dse coordination-page layout so the same annotation
process and rubric apply:

    # Coordination scene: <thread_id>
    <auto-generated header block>

    ## Juicy details       <-- placeholder for annotation pass

    ## Participants        <-- auto

    ## Full transcript     <-- auto, chronological
"""

from __future__ import annotations
import datetime as dt
import json
import re
from collections import Counter, defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
LOG_DIR = ROOT / "agent-logs"
OUT_DIR = Path(__file__).resolve().parent / "outputs" / "threads"
CANDIDATES = Path(__file__).resolve().parent / "outputs" / "candidates.jsonl"

# Reuse the load pipeline from build_candidates so time-fills (body ts,
# wayback capture) apply consistently.
sys_path_head = str(Path(__file__).resolve().parent)
import sys as _sys
if sys_path_head not in _sys.path:
    _sys.path.insert(0, sys_path_head)
from build_candidates import load_host as _load_host_full  # noqa: E402

AT_RE = re.compile(r"@(agent[-\w]+)", re.I)


def load_host(host):
    return {r["page_id"]: r for r in _load_host_full(host)}


def format_duration(a, b):
    if not a or not b:
        return "unknown"
    ta = dt.datetime.fromisoformat(a)
    tb = dt.datetime.fromisoformat(b)
    delta = tb - ta
    total_min = int(delta.total_seconds() // 60)
    h, m = divmod(total_min, 60)
    if h:
        return f"{h}h{m:02d}"
    return f"{m}m"


def render_body(body):
    if not body:
        return "> _(empty body)_"
    lines = body.splitlines() or [body]
    return "\n".join(f"> {line}" if line else ">" for line in lines)


def render_thread(cand, revs_by_id):
    members = [revs_by_id[pid] for pid in cand["paste_ids"] if pid in revs_by_id]
    members.sort(key=lambda r: (r.get("time") or "", r.get("page_id")))

    labels = Counter(m.get("label") or "?" for m in members)
    at_targets = Counter()
    at_by_author = defaultdict(Counter)
    for m in members:
        body = m.get("body") or ""
        for tgt in AT_RE.findall(body):
            at_targets[tgt.lower()] += 1
            at_by_author[(m.get("label") or "?").lower()][tgt.lower()] += 1

    duration = format_duration(cand["first_write"], cand["last_write"])
    lines = []
    lines.append(f"# Coordination scene: {cand['thread_id']}")
    lines.append("")
    lines.append(f"Host: `{cand['host']}`  ")
    lines.append(
        f"Time window: {cand['first_write']} to {cand['last_write']}  ({duration})  "
    )
    lines.append(f"Pastes: {cand['n_pastes']}  ")
    lines.append(f"Distinct writer labels: {cand['n_distinct_labels']}  ")
    lines.append(f"@-handle mentions: {cand['n_at_mentions']}  ")
    if cand.get("top_titles"):
        lines.append("Common titles: " + ", ".join(f"`{t}`" for t in cand["top_titles"][:8]))
    lines.append("")

    lines.append("## Juicy details")
    lines.append("")
    lines.append("_(placeholder — annotation pass fills this in)_")
    lines.append("")

    lines.append("## Participants")
    lines.append("")
    lines.append("| label | pastes | first | last | @-targets |")
    lines.append("|---|---:|---|---|---|")
    label_stats = defaultdict(lambda: {"n": 0, "first": None, "last": None})
    for m in members:
        lab = m.get("label") or "?"
        s = label_stats[lab]
        s["n"] += 1
        t = m.get("time")
        if t and (s["first"] is None or t < s["first"]):
            s["first"] = t
        if t and (s["last"] is None or t > s["last"]):
            s["last"] = t
    for lab, s in sorted(label_stats.items(), key=lambda kv: -kv[1]["n"]):
        targets = at_by_author.get(lab.lower(), Counter())
        target_str = ", ".join(f"@{t}({n})" for t, n in targets.most_common()) or "-"
        lines.append(
            f"| `{lab}` | {s['n']} | {s['first'] or '?'} | {s['last'] or '?'} | {target_str} |"
        )
    lines.append("")

    lines.append(f"## Full transcript ({len(members)} pastes, chronological)")
    lines.append("")
    for i, m in enumerate(members, 1):
        t = m.get("time") or "(no time)"
        lab = m.get("label") or "?"
        title = m.get("source_title") or ""
        pid = m.get("page_id", "").split("/", 1)[-1]
        lines.append(f"### #{i} — {t} — `{lab}` — `{title}` — paste `{pid}`")
        lines.append("")
        lines.append(render_body(m.get("body") or ""))
        lines.append("")

    return "\n".join(lines)


def main():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    cands = [json.loads(l) for l in CANDIDATES.read_text().splitlines() if l]
    revs_cache = {}
    for cand in cands:
        host = cand["host"]
        if host not in revs_cache:
            revs_cache[host] = load_host(host)
        md = render_thread(cand, revs_cache[host])
        out = OUT_DIR / f"{cand['thread_id']}.md"
        out.write_text(md)
        print(f"wrote {out}  ({cand['n_pastes']} pastes)")


if __name__ == "__main__":
    main()
