#!/usr/bin/env python3
"""Target host list for the urlscan.io / urlquery.net pivot.

Each entry is (host_or_term, source, kind).

source names where the string came from:
  instructions   oai-index-scan/INSTRUCTIONS.md target-string list
  corpus         hosts that appear in agent-logs/*/revisions.jsonl bodies
  termina        swarm.termina.digital venue rows with status=candidate that
                 no corpus in this repo holds
  thecolony      leads recorded in analyses/thecolony-ai/README.md

kind is how the term is searched:
  host   urlscan `domain:<host>`; urlquery free-text `<host>`
  term   urlscan `page.url:"<term>"`; urlquery free-text `<term>`
"""

TARGETS = [
    # --- oai-index-scan/INSTRUCTIONS.md ---------------------------------
    ("md.succ.ai", "instructions", "host"),
    ("vanderbi.lt", "instructions", "host"),
    ("bitily.in", "instructions", "host"),
    ("yourls.pro", "instructions", "host"),
    ("yourls.shop", "instructions", "host"),
    ("yourls.website", "instructions", "host"),
    ("yourls.space", "instructions", "host"),
    ("goto.unm.edu", "instructions", "host"),
    ("r.jina.ai", "instructions", "host"),
    ("httpbin.org", "instructions", "host"),
    ("allorigins.hexlet.app", "instructions", "host"),
    ("da.gd", "instructions", "host"),
    ("markdown.new", "instructions", "host"),
    ("pure.md", "instructions", "host"),
    ("proxymule.com", "instructions", "host"),
    ("jqp.vercel.app", "instructions", "host"),
    ("api.microlink.io", "instructions", "host"),
    ("cors-get-proxy.sirjosh.workers.dev", "instructions", "host"),
    ("cors.bwa.workers.dev", "instructions", "host"),
    ("cors.ripka.workers.dev", "instructions", "host"),
    ("jsonhero.io", "instructions", "host"),
    ("urltomarkdown", "instructions", "term"),
    # --- hosts seen in agent-logs bodies --------------------------------
    ("wikiservice.at", "corpus", "host"),
    ("tmcleod.org", "corpus", "host"),
    ("texteditors.org", "corpus", "host"),
    ("usemod.org", "corpus", "host"),
    ("ludism.org", "corpus", "host"),
    ("prowiki.org", "corpus", "host"),
    ("dorfwiki.org", "corpus", "host"),
    ("api.counterapi.dev", "corpus", "host"),
    ("countapi.mileshilliard.com", "corpus", "host"),
    ("rmn.re", "corpus", "host"),
    ("lnkr.click", "corpus", "host"),
    ("url.popcat.xyz", "corpus", "host"),
    ("uoft.me", "corpus", "host"),
    ("u.ethz.ch", "corpus", "host"),
    ("md.dhr.wtf", "corpus", "host"),
    ("webcrawlerapi.com", "corpus", "host"),
    ("corsmirror.com", "corpus", "host"),
    ("cors.hypnguyen.workers.dev", "corpus", "host"),
    ("cloudflare-cors-anywhere.hanpengchen.workers.dev", "corpus", "host"),
    ("test.cors.workers.dev", "corpus", "host"),
    ("proxy.corsfix.com", "corpus", "host"),
    ("api.cors.lol", "corpus", "host"),
    ("api.allorigins.win", "corpus", "host"),
    ("platform.lemino.ai", "corpus", "host"),
    ("www-sec-gov.translate.goog", "corpus", "host"),
    ("www-investor-gov.translate.goog", "corpus", "host"),
    ("paste.linuxiarz.pl", "corpus", "host"),
    ("pastebin.k4be.pl", "corpus", "host"),
    ("pastebin.tarcseh.me", "corpus", "host"),
    ("anna.fyi", "corpus", "host"),
    ("2md.link", "corpus", "host"),
    ("vnr.st", "corpus", "host"),
    ("site-test.nsi.bg", "corpus", "host"),
    ("data.idph.state.ia.us", "corpus", "host"),
    ("county.json", "corpus", "term"),
    ("regCF_county", "corpus", "term"),
    # --- termina candidate venues not held in this repo -----------------
    ("yourls.pl", "termina", "host"),
    ("yourls.biz", "termina", "host"),
    ("zapro.si", "termina", "host"),
    ("kodak.love", "termina", "host"),
    ("klickhier.at", "termina", "host"),
    ("ativar.abre.bio", "termina", "host"),
    ("easylinkref.com", "termina", "host"),
    ("linkrutgon.net", "termina", "host"),
    ("t.mdcdev.me", "termina", "host"),
    ("2dd.pl", "termina", "host"),
    ("cors-proxy-gray.vercel.app", "termina", "host"),
    ("thenacken-python-cors-proxy.hf.space", "termina", "host"),
    ("md.coredump.ch", "termina", "host"),
    ("campusosttirol.mustertheorie.de", "termina", "host"),
    ("kb5.zukunftslernorte.org", "termina", "host"),
    ("netzwerkgegengewalt.org", "termina", "host"),
    ("schulwiki.org", "termina", "host"),
    ("nervesocket.com", "termina", "host"),
    ("minetest.wjake.com", "termina", "host"),
    ("paste.probyte.ee", "termina", "host"),
    ("paste.ubuntu.org.cn", "termina", "host"),
    # --- thecolony.ai / Centaur leads -----------------------------------
    ("pinggy-free.link", "thecolony", "host"),
    ("openagentchat.net", "thecolony", "host"),
    ("public-board.com", "thecolony", "host"),
    ("help-peer.hyperplex.org", "thecolony", "host"),
    # --- round 2: hosts and strings surfaced by the round-1 harvest ---------
    # Wrapper and sink hosts seen inside round-1 rows or smuggled scripts.
    ("markdown.microlink.io", "round2", "host"),
    ("text.microlink.io", "round2", "host"),
    ("html.microlink.io", "round2", "host"),
    ("iad.microlink.io", "round2", "host"),
    ("pdf.microlink.io", "round2", "host"),
    ("httpbingo.org", "round2", "host"),
    ("httpbun.com", "round2", "host"),
    ("deelay.me", "round2", "host"),
    ("cors.io", "round2", "host"),
    ("cors-proxy-xi-ten.vercel.app", "round2", "host"),
    ("api.codetabs.com", "round2", "host"),
    ("corsproxy.io", "round2", "host"),
    ("cors.isomorphic-git.org", "round2", "host"),
    ("everyorigin.deno.dev", "round2", "host"),
    ("web2md.site", "round2", "host"),
    ("urltomarkdown.herokuapp.com", "round2", "host"),
    ("please.untaint.us", "round2", "host"),
    ("rt.http3.lol", "round2", "host"),
    ("arquivo.pt", "round2", "host"),
    ("datawrapper.dwcdn.net", "round2", "host"),
    ("ntfy.envs.net", "round2", "host"),
    ("pie.dev", "round2", "host"),
    ("v1.boomlify.com", "round2", "host"),
    ("webhook.site", "round2", "host"),
    ("sho.rt", "round2", "host"),
    # Data targets of the round-1 clusters, searched to expose wrappers we
    # do not know yet.
    ("public.tableau.com", "round2", "host"),
    ("vizprod.aihw.gov.au", "round2", "host"),
    ("viz.aihw.gov.au", "round2", "host"),
    ("unctadstat-api.unctad.org", "round2", "host"),
    ("unctadstat.unctad.org", "round2", "host"),
    ("thrill-data.com", "round2", "host"),
    ("acleddata.com", "round2", "host"),
    ("whssgr.com", "round2", "host"),
    ("whssgrgupkar.com", "round2", "host"),
    ("whstrustpkl.com", "round2", "host"),
    ("history.powys.org.uk", "round2", "host"),
    ("nmdigital.unm.edu", "round2", "host"),
    ("alexandria.ucsb.edu", "round2", "host"),
    ("eurogamer.net", "round2", "host"),
    ("preservinglocalhistory.recollectcms.com", "round2", "host"),
    ("macrotrends.net", "round2", "host"),
    ("lookerstudio.google.com", "round2", "host"),
    ("datastudio.google.com", "round2", "host"),
    # Tell strings. The base64 prefixes are "<!doctype", "<html", "<script",
    # "<body", "<div": smuggled HTML on any host that decodes base64 paths.
    ("showVizHome", "round2", "term"),
    ("yourls-api.php", "round2", "term"),
    ("httpbin.org/base64/", "round2", "term"),
    ("base64/PCFkb2N0eXBl", "round2", "term"),
    ("base64/PGh0bWw", "round2", "term"),
    ("base64/PHNjcmlwdD", "round2", "term"),
    ("base64/PGJvZHk", "round2", "term"),
    ("base64/PGRpdi", "round2", "term"),
    (":~:text=", "round2", "term"),
    # --- round 3: direct data-target hosts and sinks that jombb's receipts
    # cover and round 1 did not search directly ------------------------------
    ("viz.aihw.gov.au", "round3", "host"),
    ("vizhub.healthdata.org", "round3", "host"),
    ("portal.max.gov", "round3", "host"),
    ("piv.max.gov", "round3", "host"),
    ("login.max.gov", "round3", "host"),
    ("api.datausa.io", "round3", "host"),
    ("api-la.datausa.io", "round3", "host"),
    ("api-kona.datausa.io", "round3", "host"),
    ("api.usaspending.gov", "round3", "host"),
    ("api.dataafrica.io", "round3", "host"),
    ("api.worldpoverty.io", "round3", "host"),
    ("px.hagstofa.is", "round3", "host"),
    ("api.beta.ons.gov.uk", "round3", "host"),
    ("rspace.library.cofc.edu", "round3", "host"),
    ("finance.yahoo.co.jp", "round3", "host"),
    ("itty.bitty.site", "round3", "host"),
    ("nghttp2.org", "round3", "host"),
    ("backlink-generator-tool.github.io", "round3", "host"),
    ("digital.eventguides.co.uk", "round3", "host"),
    ("sec.gov/files/", "round3", "term"),
    ("sec.gov/cgi-bin/", "round3", "term"),
    ("docs.google.com/spreadsheets", "round3", "term"),
    ("tesseract/data", "round3", "term"),
]

# Hosts whose scan volume is dominated by unrelated traffic. The scripts
# restrict these to the incident window instead of pulling all-time rows.
GENERIC_HOSTS = {
    "r.jina.ai", "httpbin.org", "da.gd", "jsonhero.io", "api.microlink.io",
    "allorigins.hexlet.app", "api.allorigins.win", "markdown.new", "pure.md",
    "webcrawlerapi.com", "proxymule.com", "county.json",
    "arquivo.pt", "webhook.site", "public.tableau.com", "lookerstudio.google.com",
    "datastudio.google.com", "corsproxy.io", "eurogamer.net", "macrotrends.net",
    "showVizHome", "yourls-api.php", "base64/PGh0bWw", "base64/PHNjcmlwdD",
    "base64/PGJvZHk", "base64/PGRpdi", "base64/PCFkb2N0eXBl", ":~:text=",
    "api.datausa.io", "api.usaspending.gov", "finance.yahoo.co.jp", "nghttp2.org",
    "sec.gov/files/", "sec.gov/cgi-bin/", "docs.google.com/spreadsheets", "tesseract/data",
}

INCIDENT_WINDOW_START = "2026-03-01"
