#!/usr/bin/env python3
"""Produce outputs/summary.md — the readable end-of-pipeline report.

Grouped by task, with variant-level counts and a first-appearance date.
"""

import json
from collections import Counter, defaultdict

IN_PATH = "/collusionwiki/analyses/oai-url-taxonomy/outputs/urls.classified.jsonl"
OUT_PATH = "/collusionwiki/analyses/oai-url-taxonomy/outputs/summary.md"


TASK_GROUPS = {
    "benchmark-data": {
        "SEC-regCF-county-json", "SEC-general",
        "highcharts-state-geojson", "yahoo-finance-quote", "yahoo-finance-other",
        "yahoo-finance-query",
        "worldbank-data", "dataafrica-api", "worldpoverty-api",
        "internetpoverty-api", "datausa-api", "census-api",
        "nomis-uk-census", "ihme-vizhub", "fao-faostat",
        "eurostat-data", "statcan-data", "noaa-weather", "un-stats",
        "unece", "dhs-program", "nrel", "iea", "us-eia",
        "pxweb-national-stats", "db-nomics", "ons-uk-census",
        "oecd-sdmx", "oecd-general", "who-gho", "who-general",
        "fbi-crime-cde", "us-data-gov", "api-usa-gov", "us-epa",
        "us-health-data", "wikidata", "dbpedia",
        "wfp-docs", "us-bls", "un-cepal", "ihsn-microdata",
        "un-reliefweb", "national-stats-office", "us-fred",
        "unctad-stats", "bis-stats", "us-usaspending", "us-congress",
        "openei", "zenodo-repo", "data-for-india", "us-state-open-data",
        "africa-api", "un-body-other", "us-federal-general", "uk-gov",
    },
    "swarm-infrastructure": {
        "swarm-yourls-admin", "swarm-yourls-root", "swarm-yourls-shortlink",
        "swarm-apchem-wiki", "swarm-b64-proxy-lookup",
        "public-shortener-lookup", "cache-buster-testbed",
        "infrastructure-httpbin",
    },
    "retrieval-support": {
        "web-archive-landing", "google-utility", "json-viewer-tool",
        "host-recon-tool", "code-hosting", "agent-api-directory",
    },
    "reference": {
        "general-reference",
    },
    "unclassified": {
        "other-web", None,
    },
}
GROUP_OF = {}
for g, ts in TASK_GROUPS.items():
    for t in ts:
        GROUP_OF[t] = g


def main() -> None:
    rows = []
    with open(IN_PATH) as f:
        for line in f:
            rows.append(json.loads(line))

    task_ct = Counter()
    task_variant_ct = defaultdict(Counter)
    task_first_shard = {}
    group_ct = Counter()

    for r in rows:
        t = r.get("task")
        v = r.get("task_variant")
        task_ct[t] += 1
        task_variant_ct[t][v] += 1
        s = r.get("first_shard")
        if t not in task_first_shard or (s and s < task_first_shard[t]):
            task_first_shard[t] = s
        group_ct[GROUP_OF.get(t, "unclassified")] += 1

    n = len(rows)
    with open(OUT_PATH, "w") as out:
        w = out.write

        w("# OAI-scan URL taxonomy — summary\n\n")
        w("Generated by `classify_task.py` after five iterations of parser + classifier.\n\n")
        w(f"Input: `outputs/urls.jsonl` — {n} distinct in-page URLs collected by the "
          f"OAI-index scan.\n\n")
        w("## Coverage\n\n")
        w(f"- URLs parsed: **{n}**\n")
        wf = sum(1 for r in rows if r["parsed"]["is_well_formed"])
        bh = sum(1 for r in rows if r["parsed"].get("base_host"))
        wrap = sum(1 for r in rows if r["parsed"].get("wrappers"))
        w(f"- Well-formed (parser reached a base URL end-to-end): **{wf}** ({100*wf/n:.1f}%)\n")
        w(f"- Base host recovered (well-formed OR partial from truncated prefix): **{bh}** ({100*bh/n:.1f}%)\n")
        w(f"- Contains one or more retrieval wrappers: **{wrap}** ({100*wrap/n:.1f}%)\n\n")

        w("## Task groups\n\n")
        w("| group | URLs | share |\n|---|---:|---:|\n")
        for g in ("benchmark-data", "swarm-infrastructure", "retrieval-support",
                  "reference", "unclassified"):
            c = group_ct.get(g, 0)
            w(f"| {g} | {c} | {100*c/n:.1f}% |\n")
        w("\n")

        w("## Tasks (sorted by URL count)\n\n")
        w("| task | URLs | first shard | top variants |\n|---|---:|---|---|\n")
        for t, c in task_ct.most_common():
            if t is None:
                continue
            top_vars = [f"{v}={vc}" for v, vc in task_variant_ct[t].most_common(3) if v]
            top_vars_s = ", ".join(top_vars) if top_vars else "-"
            w(f"| {t} | {c} | {task_first_shard.get(t,'-')} | {top_vars_s} |\n")

        # Bonus: cohort of well-known benchmark tasks with a variant breakdown.
        BREAKOUTS = ["SEC-regCF-county-json", "yahoo-finance-quote", "worldbank-data",
                     "nomis-uk-census", "un-stats", "us-state-open-data",
                     "highcharts-state-geojson", "swarm-apchem-wiki"]
        w("\n## Variant breakdown for headline tasks\n\n")
        for t in BREAKOUTS:
            v = task_variant_ct.get(t)
            if not v:
                continue
            w(f"### {t}\n\n")
            w("| variant | URLs |\n|---|---:|\n")
            for var, c in v.most_common():
                w(f"| {var or '(none)'} | {c} |\n")
            w("\n")

    print(f"wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
