#!/usr/bin/env node
'use strict';
const fs=require('fs'),path=require('path');
const ROOT=path.resolve(__dirname,'..'),RAW=path.join(ROOT,'tmp/raw'),SCR=path.join(ROOT,'tmp/scratch'),OUT=path.join(ROOT,'results/shards');
const week=process.argv[2]; if(!week) throw Error('usage: reprocess_current_week.js WEEK');
const targets=['md.succ.ai','vanderbi.lt','bitily.in','yourls.pro','yourls.shop','yourls.website','yourls.space','goto.unm.edu','r.jina.ai','httpbin.org','allorigins.hexlet.app','da.gd','markdown.new','pure.md','proxymule.com','urlquery.net','jqp.vercel.app','api.microlink.io','cors-get-proxy','cors.bwa.workers.dev','cors.ripka.workers.dev','jsonhero.io','urltomarkdown'];
const rkeys=['published_date','modified_date','cache_age','page_title','page_url','urls_in_page','first_seen_query','matched_target_strings'],qkeys=['group_number','query_sequence','search_mode','query','returned_result_count','retained_result_count','new_page_count','cumulative_page_count','new_distinctive_leads'];
const uniq=a=>[...new Set(a)],order=(o,k)=>Object.fromEntries(k.map(x=>[x,o[x]]));
function blocks(s){return s.split(/-{20,}/).filter(b=>/citeturn\d+(?:search|news)\d+/.test(b));}
function parse(b,q,connected){const low=b.toLowerCase(),literal=targets.filter(t=>low.includes(t.toLowerCase()));if(!literal.length)return null;const mats=uniq([...literal,...connected.filter(t=>low.includes(t.toLowerCase()))]);const ci=b.search(/\n?citeturn\d+(?:search|news)\d+/),h=b.slice(0,ci).trim(),m=h.match(/^([\s\S]*?) \((https?:\/\/[^)]+)\)$/);if(!m)return null;const cr=(b.match(/\bCrawled:\s*([^;\n]+)/)||[])[1]||null;return order({published_date:(b.match(/\bPublished:\s*([^;\n]+)/)||[])[1]||null,modified_date:(b.match(/\bModified:\s*([^;\n]+)/)||[])[1]||null,cache_age:cr?`Crawled: ${cr}`:null,page_title:m[1],page_url:m[2],urls_in_page:uniq((b.match(/https?:\/\/[^\s<>"'`)]+/g)||[]).filter(u=>!/^https?:\/\/\]/.test(u))),first_seen_query:q,matched_target_strings:mats},rkeys)}
function merge(a,b){const o={...a,urls_in_page:uniq([...a.urls_in_page,...b.urls_in_page]),matched_target_strings:uniq([...a.matched_target_strings,...b.matched_target_strings])};for(const k of ['published_date','modified_date','cache_age','page_title'])if(o[k]===null&&b[k]!==null)o[k]=b[k];return order(o,rkeys)}
const qfiles=fs.readdirSync(SCR).filter(n=>n.startsWith(week+'.group_')&&n.endsWith('.queries.jsonl')).sort(),state=new Map(),ledger=[],connected=[];let failures=0,excluded=0;
for(let i=0;i<qfiles.length;i++){const n=i+1,p=String(n).padStart(3,'0'),old=JSON.parse(fs.readFileSync(path.join(SCR,`${week}.group_${p}.queries.jsonl`),'utf8').trim()),raw=fs.readFileSync(path.join(RAW,`${week}.group_${p}.txt`),'utf8'),bs=blocks(raw),kept=[];if(n>92)for(const x of (old.query.match(/"([^"]+)"/g)||[]).map(x=>x.slice(1,-1)))if(!connected.includes(x))connected.push(x);for(const b of bs){const x=parse(b,old.query,connected);if(x)kept.push(x);else excluded++;}const delta=[];let news=0;for(const x of kept){const prior=state.get(x.page_url);if(!prior){state.set(x.page_url,x);delta.push(x);news++;}else{const m=merge(prior,x);if(JSON.stringify(m)!==JSON.stringify(prior)){state.set(x.page_url,m);delta.push(m)}}}const qr=order({group_number:n,query_sequence:n,search_mode:old.search_mode||'search_query',query:old.query,returned_result_count:bs.length,retained_result_count:kept.length,new_page_count:news,cumulative_page_count:state.size,new_distinctive_leads:Array.isArray(old.new_distinctive_leads)?uniq(old.new_distinctive_leads):[]},qkeys);ledger.push(qr);fs.writeFileSync(path.join(SCR,`${week}.group_${p}.queries.jsonl`),JSON.stringify(qr)+'\n');fs.writeFileSync(path.join(SCR,`${week}.group_${p}.results.jsonl`),delta.map(JSON.stringify).join('\n')+(delta.length?'\n':''));}
const results=[...state.values()];fs.mkdirSync(OUT,{recursive:true});fs.writeFileSync(path.join(OUT,week+'.queries.jsonl'),ledger.map(JSON.stringify).join('\n')+'\n');fs.writeFileSync(path.join(OUT,week+'.results.jsonl'),results.map(JSON.stringify).join('\n')+'\n');
let drought=0;for(let i=ledger.length-1;i>=0&&ledger[i].new_page_count===0&&!ledger[i].new_distinctive_leads.length;i--)drought++;
console.log(JSON.stringify({week,queries:ledger.length,records:results.length,urls_in_page:results.reduce((n,r)=>n+r.urls_in_page.length,0),truncated:results.reduce((n,r)=>n+r.urls_in_page.filter(u=>/\.\.\.|…|\[\.\.\.\]/.test(u)).length,0),excluded_blocks:excluded,parser_failures:failures,final_drought:drought},null,2));
